sonar.projectKey=chatagent
sonar.projectName=ChatAgent
sonar.projectVersion=0.0.1

sonar.sources=src/main
sonar.tests=src/test
sonar.sourceEncoding=UTF-8

sonar.java.source=21
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/config/**,**/entity/**
sonar.test.exclusions=**/test/**

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S101
sonar.issue.ignore.multicriteria.e1.resourceKey=**
