spring:
  application:
    name: mcp-websearch-server
  ai:
    mcp:
      server:
        name: websearch-server
        version: 0.0.1
        type: ASYNC
        sse-message-endpoint: /mcp/message

server:
  port: 8081

google:
  search:
    api-key: ${GOOGLE_API_KEY:}
    cx: ${GOOGLE_SEARCH_CX:}
    endpoint: https://www.googleapis.com/customsearch/v1
    num-results: 10
